import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "alacritty-direct"

[shell]
# program = "zellij"
program = "/usr/local/bin/zsh"
# args = ["-l", "welcome"]
args = ["--login"]

[window]
dynamic_padding = true
# startup_mode = "Fullscreen"
option_as_alt = "Both"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 12

[selection]
save_to_clipboard = true
