# A minimal left prompt
# format = """$directory$character"""

palette = "custom_catppuccin"

command_timeout = 1200

format = """
$username\
$hostname\
$localip\
$shlvl\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$character"""

right_format = "$all"

[time]
time_format = "%R"
format = "  $time($style) "
style = "bright-white"
disabled = false

[character]
success_symbol = "[❯](blue)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[git_branch]
style = "purple"

[aws]
symbol = " "

[golang]
symbol = " "

[docker_context]
symbol = "  "

[python]
symbol = " "

[palettes.custom_catppuccin]
rosewater = "#F29D9D"
flamingo = "#F29D9D"
pink = "#F29D9D"
purple = "#AD6FF7"
mauve = "#AD6FF7"
red = "#E66767"
maroon = "#E66767"
peach = "#FAB770"
yellow = "#FACA64"
green = "#70CF67"
teal = "#4CD4BD"
sky = "#00BBCC"
sapphire = "#61BDFF"
blue = "#00BFFF"
lavender = "#C1C9E6"
text = "#C1C9E6"
subtext1 = "#A3AAC2"
subtext0 = "#A3AAC2"
overlay2 = "#464957"
overlay1 = "#464957"
overlay0 = "#464957"
surface2 = "#464957"
surface1 = "#191926"
surface0 = "#191926"
base = "#0b0b12"       # Your background color
mantle = "#0b0b12"
crust = "#191926"
