return {
    -- Twilight for dimming unfocused text (note-specific configuration)
    -- {
    --     "folke/twilight.nvim",
    --     cond = function()
    --         return vim.g.nvim_mode == "notes"
    --     end,
    --     opts = {
    --         dimming = {
    --             alpha = 0.25,
    --             color = { "Normal", "#ffffff" },
    --             term_bg = "#000000",
    --             inactive = false,
    --         },
    --         context = 10,
    --         treesitter = true,
    --     },
    -- },
    -- -- Notes-specific snacks scope configuration
    -- {
    --     "folke/snacks.nvim",
    --     priority = 1000,
    --     lazy = false,
    --     cond = function()
    --         return vim.g.nvim_mode == "notes"
    --     end,
    --     opts = {
    --         scope = {
    --             enabled = true,
    --             show_start = true,
    --             show_end = true,
    --             injected_languages = true,
    --             highlight = "Function",
    --             priority = 500,
    --         },
    --     },
    --     keys = {
    --         -- Scope navigation
    --         { "<leader>ss", function() require("snacks").scope.show() end, desc = "Show Scope" },
    --         { "<leader>sh", function() require("snacks").scope.hide() end, desc = "Hide Scope" },
    --         { "<leader>st", function() require("snacks").scope.toggle() end, desc = "Toggle Scope" },
    --     },
    -- },
}

